### ISSUE TITLE
Duplicating to Other Beacons Increases Quality

### ISSUE THREAD

**Issue by Cyrcle** [thommcgrath/Beacon-For-Ark#4]
I just finished my "master" beacon loot table for white-red beacon drops.  I then went to duplicate them to the bonus beacons, cave beacons, etc. and noticed that all the item qualities went up a notch or two automatically.  

I know you probably coded this to do it intentionally.  Maybe make it an option down the line when duplicating, because now I'm spending time readjusting all of the item qualities.  <3

**Comment by thommcgrath** [comment]
It's semi-intentional. Each loot source has a hidden multiplier. So moving definitions between loot sources will have this effect. What I need to do is stop storing the quality as a number and use the label instead, so the set can compute the correct quality for the loot source it belongs to.
