### ISSUE TITLE
[Feature Request] Save Item sets as Presets

### ISSUE THREAD

**Issue by JamieKG** [thommcgrath/Beacon-For-Ark#6]
Hi I found this program on Reddit had a play with it now using it for my server Thanks for the work you put into it

So to my Question is there away we could add import and export our own presets for the item sets ?

Thanks JamieKG

**Comment by thommcgrath** [comment]
Great suggestion. So great in fact, that I checked in the code for this feature last night: https://github.com/thommcgrath/Beacon-For-Ark/commit/c42394d382bb9ed7c2795c0c1a3b36752f3525dd

It'll be available in build 4, though I don't know when I'll have that ready.

**Comment by JamieKG** [comment]
excellent thanks for your hard work :)
